title: "API Documentation"
description: "Documentation for My Project API"
theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"
# Enable the sidebar navigation
just_the_docs:
  sidebar:
    nav_order: 1
    links:
      - text: "Home"
        url: "/"
      - text: "API Endpoints"
        url: "/endpoints/"
