title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable the sidebar navigation
just_the_docs:
  sidebar:
    nav_order: 1
    links:
      - text: "Home"
        url: "/"
      - text: "API Endpoints"
        url: "/endpoints/"